spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/spring-security-auditing
    username: root
    password:
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect

server:
  port: 10


application:
  security:
    jwt:
      secret-key: 763151654a285942553b587d5f5753445b2f66426b285748414b575149
      expiration: 360000
      refresh-token:
        expiration: 60480000
